def build_markdown_report(records):
  """Generate a markdown table report of student performance.
  
  Args:
    records: List of dicts with keys: nim, nama, hadir, akhir, predikat
    
  Returns:
    String containing formatted markdown table
  """
  if not records:
    return "# Rekap Nil" \
    "i Mahasiswa\n\nTidak ada data mahasiswa.\n\nGenerated by student_performance_tracker"
  
  report_lines = [
    "# Rekap Nilai Mahasiswa",
    "| NIM | Nama | Hadir (%) | Nilai Akhir | Predikat |",
    "|---|---|---:|---:|:---:|"
  ]
  
  for record in records:
    line = "| {} | {} | {:.1f} | {:.2f} | {} |".format(
      record['nim'],
      record['nama'],
      record['hadir'],
      record['akhir'],
      record['predikat']
    )
    report_lines.append(line)
  
  report_lines.append("Generated by student_performance_tracker")
  
  return "\n".join(report_lines)

def build_html_report(records):
  """Generate an HTML report with color-coded grades.
  
  Args:
    records: List of dicts with keys: nim, nama, hadir, akhir, predikat
    
  Returns:
    String containing formatted HTML
  """
  if not records:
    return "<html><body><h1>Rekap Nilai Mahasiswa</h1><p>Tidak ada data mahasiswa.</p></body></html>"
  
  # Warna untuk setiap predikat
  colors = {
    'A': '#28a745',  # Hijau
    'B': '#17a2b8',  # Biru
    'C': '#ffc107',  # Kuning
    'D': '#fd7e14',  # Orange
    'E': '#dc3545'   # Merah
  }
  
  html = """<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rekap Nilai Mahasiswa</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 20px;
            background-color: #f5f5f5;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background-color: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        h1 {
            color: #333;
            text-align: center;
            margin-bottom: 30px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #007bff;
            color: white;
            padding: 12px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 10px 12px;
            border-bottom: 1px solid #ddd;
        }
        tr:hover {
            background-color: #f8f9fa;
        }
        .predikat {
            font-weight: bold;
            text-align: center;
            padding: 5px 10px;
            border-radius: 5px;
            color: white;
        }
        .text-right {
            text-align: right;
        }
        .footer {
            text-align: center;
            color: #666;
            font-size: 12px;
            margin-top: 20px;
        }
        .stats {
            display: flex;
            justify-content: space-around;
            margin-bottom: 30px;
        }
        .stat-box {
            text-align: center;
            padding: 15px;
            background-color: #f8f9fa;
            border-radius: 8px;
            min-width: 150px;
        }
        .stat-number {
            font-size: 32px;
            font-weight: bold;
            color: #007bff;
        }
        .stat-label {
            color: #666;
            font-size: 14px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>📊 Rekap Nilai Mahasiswa</h1>
        
        <div class="stats">
            <div class="stat-box">
                <div class="stat-number">{}</div>
                <div class="stat-label">Total Mahasiswa</div>
            </div>
            <div class="stat-box">
                <div class="stat-number">{:.2f}</div>
                <div class="stat-label">Rata-rata Nilai</div>
            </div>
            <div class="stat-box">
                <div class="stat-number">{:.1f}%</div>
                <div class="stat-label">Rata-rata Kehadiran</div>
            </div>
        </div>
        
        <table>
            <thead>
                <tr>
                    <th>NIM</th>
                    <th>Nama</th>
                    <th class="text-right">Kehadiran (%)</th>
                    <th class="text-right">Nilai Akhir</th>
                    <th style="text-align: center;">Predikat</th>
                </tr>
            </thead>
            <tbody>
""".format(
    len(records),
    sum(r['akhir'] for r in records) / len(records),
    sum(r['hadir'] for r in records) / len(records)
  )
  
  for record in records:
    color = colors.get(record['predikat'], '#6c757d')
    html += """                <tr>
                    <td>{}</td>
                    <td>{}</td>
                    <td class="text-right">{:.1f}</td>
                    <td class="text-right">{:.2f}</td>
                    <td style="text-align: center;"><span class="predikat" style="background-color: {}">{}</span></td>
                </tr>
""".format(
      record['nim'],
      record['nama'],
      record['hadir'],
      record['akhir'],
      color,
      record['predikat']
    )
  
  html += """            </tbody>
        </table>
        
        <div class="footer">
            Generated by student_performance_tracker
        </div>
    </div>
</body>
</html>"""
  
  return html

def save_text(path, content):
  """Save the given content to a text file."""
  with open(path, 'w', encoding='utf-8') as file:
    file.write(content) 