def build_markdown_report(records):
  if not records:
    msg = "# Rekap Nilai Mahasiswa\n\nTidak ada data mahasiswa.\n\n"
    msg += "Generated by student_performance_tracker"
    return msg
  
  report_lines = []
  report_lines.append("# Rekap Nilai Mahasiswa")
  report_lines.append("| NIM | Nama | Hadir (%) | Nilai Akhir | Predikat |")
  report_lines.append("|---|---|---:|---:|:---:|")
  
  for record in records:
    line = "| {0} | {1} | {2:.1f} | {3:.2f} | {4} |".format(
      record['nim'], record['nama'], record['hadir'], 
      record['akhir'], record['predikat'])
    report_lines.append(line)
  
  report_lines.append("Generated by student_performance_tracker")
  return "\n".join(report_lines)

def build_html_report(records):
  if not records:
    return "<html><body><h1>Rekap Nilai</h1><p>Tidak ada data.</p></body></html>"
  
  colors = {'A': '#28a745', 'B': '#17a2b8', 'C': '#ffc107', 'D': '#fd7e14', 'E': '#dc3545'}
  total = len(records)
  avg_nilai = sum(r['akhir'] for r in records) / total
  avg_hadir = sum(r['hadir'] for r in records) / total
  
  html = []
  html.append("<!DOCTYPE html><html><head><meta charset=UTF-8>")
  html.append("<title>Rekap Nilai</title><style>")
  html.append("body{font-family:Arial;margin:20px;background:#f5f5f5}")
  html.append(".container{max-width:1200px;margin:0 auto;background:white;padding:30px;border-radius:10px}")
  html.append("h1{text-align:center;color:#333}table{width:100%;border-collapse:collapse;margin:20px 0}")
  html.append("th{background:#007bff;color:white;padding:12px}td{padding:10px;border-bottom:1px solid #ddd}")
  html.append(".predikat{font-weight:bold;padding:5px 10px;border-radius:5px;color:white}")
  html.append(".text-right{text-align:right}.stats{display:flex;justify-content:space-around;margin:20px 0}")
  html.append(".stat-box{text-align:center;padding:15px;background:#f8f9fa;border-radius:8px}")
  html.append(".stat-number{font-size:32px;font-weight:bold;color:#007bff}</style></head><body>")
  html.append("<div class=container><h1>Rekap Nilai Mahasiswa</h1><div class=stats>")
  html.append("<div class=stat-box><div class=stat-number>{0}</div><div>Total</div></div>".format(total))
  html.append("<div class=stat-box><div class=stat-number>{0:.2f}</div><div>Rata-rata Nilai</div></div>".format(avg_nilai))
  html.append("<div class=stat-box><div class=stat-number>{0:.1f}%</div><div>Rata-rata Kehadiran</div></div></div>".format(avg_hadir))
  html.append("<table><thead><tr><th>NIM</th><th>Nama</th><th>Kehadiran(%)</th><th>Nilai Akhir</th><th>Predikat</th></tr></thead><tbody>")
  
  for record in records:
    color = colors.get(record['predikat'], '#6c757d')
    html.append("<tr><td>{0}</td><td>{1}</td><td class=text-right>{2:.1f}</td><td class=text-right>{3:.2f}</td>".format(
      record['nim'], record['nama'], record['hadir'], record['akhir']))
    html.append("<td style=text-align:center><span class=predikat style=background-color:{0}>{1}</span></td></tr>".format(
      color, record['predikat']))
  
  html.append("</tbody></table><div style=text-align:center;color:#666;margin-top:20px>")
  html.append("Generated by student_performance_tracker</div></div></body></html>")
  return "".join(html)

def save_text(path, content):
  with open(path, 'w', encoding='utf-8') as file:
    file.write(content)
